- debug: var=ec2_master0_metadata_ip
  when: ec2_master0_metadata_ip is defined

- debug: var=hostvars['localhost']['ec2_master0_metadata_ip']
  when: hostvars['localhost']['ec2_master0_metadata_ip'] is defined

- name: create file
  lineinfile:
    path: /tmp/bootstrap_node
    create: yes
    line: "{{ hostvars['localhost']['ec2_master0_metadata_ip'] | string }}"

- name: Install K3S and join Worker Nodes
  shell: /usr/bin/curl -sfL https://get.k3s.io | K3S_URL="https://$(/usr/bin/grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' /tmp/bootstrap_node):6443" K3S_TOKEN="{{ K3S_TOKEN }}" sh - ; /usr/bin/sleep 30
  args:
   warn: false
